#+startup: content logdone inlneimages

#+hugo_base_dir: ../../../
#+hugo_auto_set_lastmod: t
#+HUGO_SECTION: post/2021/05
#+AUTHOR: derui

* DONE 引越しして半年経過したので振り返ってみる                        :雑記:
CLOSED: [2021-05-20 木 21:05]
:PROPERTIES:
:EXPORT_FILE_NAME: review-moving-after-a-half-year
:END:
在宅が始まってから、大分コーヒーの量(ただしかなり薄い)が増えてたので、ちょっとカフェインの摂取量を減らしてみました。まだやりはじめなので、効果が出るまではまだまだかなー。

ちょっと仕事が忙しい & 実装がいまいち進んでなくて書くことが無いので、埋め草的に、ちょうど半年が経過した引越しについて振り返ってみようかと思います。

<!--more-->

** 引越し遍歴
そういえばあんまり気にしてなかったんですが、社会人になってからの引越しを思いだしてみます。私はめんどくさいのが嫌いなので、基本的に引越しにはかなり腰が重い方です。なので件数は少ないですね。

#+begin_quote
築xx年、は入居時点です
#+end_quote

*** 一部屋目
築12年ワンルームでした。約5.5畳で、風呂・トイレがセットになっていましたね。ここはとにかく日当たりが悪く、朝の30分以外は日光が当たらないような場所でした。

#+begin_quote
学生の時に住んでいたアパートも似たようなもんでしたが。
#+end_quote

約4年半ほど住んでいました。

*** 二部屋目
築25年の1Kでした。約6.5畳(ただし0.5畳が中途半端な状態だったので、事実上6畳。ここは風呂・トイレ別になっていて、初のオール電化物件でした。

実家もオール電化ですが、自分の部屋がオール電化になると、やっぱりよい点が色々ありました。ちなみに、私はこの部屋に引っ越すまで自分の冷蔵庫というものがなかったので、引越し直後に慌ててヨドバシに走った記憶があります。

- お湯がすぐ出る
- IHなので火力とかも大体問題なし


ただ、その分電気料金が結構いくので、まー最終的にはトントンくらいでした。また、この部屋は大通りに面している場所だったので、一日中車の音がしている、というのは、慣れててもやっぱりうーんと思うときはありました。

この部屋は今迄で一番日当たりがよく(南西向き)、初めて5階という階層を経験しました。周囲に5階建以上の建物がほとんどなく、窓から日光がサンサンと降り注いでくれたので、 *もう夏はサウナ* でした。後冬でも暖房がいらんときが多々ありましたね。

約8年半住んでいました。途中で管理会社が変わったりと色々ありました。

** 今の部屋さがし
部屋探しは、約3週間程度かけておこないました。ちょっと特殊な要件があったので、まず前提となる物件が少なく、ネットだと限界があるなー・・・と思ったので、

https://www.heyagime.com/

ここに予約して行ってみることにしました。都合3回行きましたが、3回目は書類の記載をしに行ったので、事実上2回です。
色々提案してくれたり、隠れ物件を紹介してくれたりと、かなり満足度が高かったのでオススメです。

ちなみに私はあんまり迷うことが無い質で、大体一回内見に行ったら決めてしまいます。要件が特殊でそもそも選べないんじゃーというのもあるんですが。

なお、実際に部屋を決めてから引越しまでは3週間ほど空いています。これは、その当時マンションのエレベーターが工事中だったためで、さすがに5階から荷物を運び出してもらうのは・・・ということで、伸ばしました。
今の部屋が一ヶ月のフリーレントがあったので、お金的にはそれほど痛くなかったのが幸いでした。

#+begin_quote
2020/10〜11 くらいで話を聞いた感じでは、結構フリーレントは多い、という話でした。まず入居してもらわないと始まらない、ということのようです
#+end_quote

** 荷造り & 手続
ここが一番大変というかめんどくさく、元々居住空間が1畳ちょっとしか無いような状況(ゴミが多いとかではなく、テーブルとベッド + レンジ台 + スチールラックでこうなってました)だったので、まずは不用品を捨てていくところからでした。多分人生で一番物を捨てましたね。十年以上共にしたベットもここで廃棄しています。

3週間もあけておいてよかった・・・と本気で思ったのは言うまでもありません。ただ、実際には引越し日になってもまだ終わりきっておらず、業者がうまく予定をしきれておらず、午前中予定が昼から、となったので、最後に終わらせることができた、というのが実態でした・・・。

この荷造りがあるので、引越しが面倒すぎるというのが本音ですね。手続系統もめんどくさいですが、なんというかコロナのおかげで窓口がえらいガラガラだったので、移動時間の方が長いくらいで終わりました。一番面倒なのはクレカとか銀行とかの住所変更ですね。多分まだ変更しきれてないのがいくつかある。

** 引越し〜
引越し自体は、業者がテキパキとやってくれたので、搬出と搬入で合計1時間くらいしかかかってなかったんじゃないでしょうか。むしろそこから自分で出したりする方が時間かかった気がする・・・。

引っ越した部屋は今迄で一番築浅なので、色々と見たことがないものがついていました。

- 24時間換気(初めてみた)
- 画面つきインターフォン
  - 前の部屋のインターフォンは多分4年くらいずっと壊れていたので、鳴ること自体が新鮮でした
- 自動湯沸器
  - 風呂を自動で入れてくれるやつとか


ただ、24時間換気は考えものだなーとも思いました。今の建物は高断熱高気密になっているので、これがないと循環しない(そしてまた大通り沿いなので窓が開けづらい)のはわかるんですが、冬の超乾燥している空気が遠慮なく入ってくるので、 *部屋が乾燥しすぎて寝られない* というのを経験しました。

** 引越してから買ったものリスト
部屋を引っ越してから、なんか色々と古くなっているものを買いかえたり買ったりとしました。リストにしてみましょう。

- 自作PC
  - 前書きました。完全に新しくしました
- [[https://www.daikinaircon.com/ca/hg/index.html][ダイキンの空気清浄機]]
  - 加湿機能付を買いました。買った直後に除湿・加湿機能付きが出たので、そっちにしとけばよかったと思う6月直前です
- [[https://www.amazon.co.jp/gp/product/B00A1HCWCQ/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1][スピーカー]]
  - 元々のスピーカーが8年くらい使っていたので、リファインしました
  - Boseとどっちにしようか悩みましたが、あんまり低音が効きすぎるのもどうかと思ったので、バランスのとれたこっちにしてます
- [[https://www.amazon.co.jp/gp/product/B08HGNYMWZ/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1][4Kモニター x 2]]
  - モニターアーム x 2もセットです
  - 24inch x 2から 27inch x 2にレベルアップしました。机のサイズと部屋のサイズ的にはこれが上限ですね
- フライパンとか
  - せっかくガスコンロになったので、鉄フライパンを購入してみました。扱いは難しいですが、ちゃんと使えると楽しいです。
- PS5
  - 当たりました。


特に空気清浄機は、冬の超乾燥に対抗する手段としてきっちり役に立ってくれました。現状花粉症とかでは無いので、それ以外だとまぁつけておくか・・・くらいですが。

** 次の引越しはいつになるんだろうか
今の部屋は契約がちょっとだけ特殊なので、万が一だとさっさと出ていかないといけないかもしれませんが、次はもしかしたら東北に戻るかもしれないし、またどこかに行くかもしれない・・・。

そのときになってみないとわからない、というのが正直な部分なので、そのときを楽しみにしとこうと思います。まずは今の部屋を楽しもうかなと。

* comment Local Variables                                           :ARCHIVE:
# Local Variables:
# eval: (org-hugo-auto-export-mode)
# End:
