baseURL = "https://blog.deltabox.site/"
languageCode = "ja-jp"
title = "val deltabox: ('input -> blog) "
theme = "hugo-nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Works"
  weight = 30
  identifier = "works"
  url = "https://github.com/derui"

[[menu.main]]
  name = "Tags"
  weight = 40
  identifier = "tags"
  url = "/tags/"

[params]
  author = "derui"
  email = "derutakayu@gmail.com"
  github = "derui"
  paginate = 10
  avatar = "/img/avatar.png"