baseURL = "https://blog.deltabox.site/"
languageCode = "ja-jp"
title = "val deltabox: ('input -> blog) "
theme = "PaperMod"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true
googleAnalytics = false

# profile-mode
[params.profileMode]
 # needs to be explicitly set
enabled = true
title = "val deltabox: ('input -> blog)"
imageUrl = "/img/avatar.png"
imageWidth = 120
imageHeight = 120
imageTitle = "avatar"

[[params.profileMode.buttons]]
name = "Posts"
url = "posts"
[[params.profileMode.buttons]]
name = "Tags"
url = "tags"

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Works"
  weight = 30
  identifier = "works"
  url = "https://github.com/derui"

[[menu.main]]
  name = "Tags"
  weight = 40
  identifier = "tags"
  url = "/tags/"

[params]
  author = "derui"
  email = "derutakayu@gmail.com"
  github = "derui"
  paginate = 10
  avatar = "/img/avatar.png"
