[build]
publish = "public"
command = "bash -c ./deploy.sh"
[context.production.environment]
  HUGO_VERSION = "0.92.0"
  NODE_VERSION = "16.13.0"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.92.0"
  NODE_VERSION = "16.13.0"
