[build]
publish = "public"
command = "bash -c ./deploy.sh"
[context.production.environment]
  HUGO_VERSION = "0.147.9"
  NODE_VERSION = "22.16.0"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.147.9"
  NODE_VERSION = "22.16.0"
