#+startup: content logdone inlneimages

#+hugo_base_dir: ../../../
#+hugo_auto_set_lastmod: t
#+HUGO_SECTION: post/2021/06
#+AUTHOR: derui

* DONE org-roamでjournalを書いてみている                               :雑記:
CLOSED: [2021-06-05 土 15:15]
:PROPERTIES:
:EXPORT_FILE_NAME: journaling_with_org-roam
:END:
気付けば今年ももうそろそろ半分が終わろうとしている、という恐怖の事態。なんか毎年言っている気がしますが。年々早くなっている気がしますな。

今回はライトな話題で、org-roamでjournalを書くようにしてみている話です。

<!--more-->

** org-roamとは
まずパッケージの紹介ですが、 [[https://www.orgroam.com/][org-roam]] というパッケージがあります。これは、[[https://roamresearch.com/][Roam Research]]というサービスをorgに移植したものです。

Roam Researchというサービスは、 *Zettelkasten Method* というメモの方法論を基に実装されたようで、色々なメモを有機的に結合することで、知識の整理や発想を促す・・・という感じのもののようです。

org-roamはローカルでだけ動作するので、特にサーバーとか不要で、orgファイルさえ共有できれば、どこでも利用できるというのが強みですね。

#+begin_quote
ただし、検索速度とかを向上させるために、sqlite3を利用しているのと、グラフを作成するのにgraphizを利用しているので、それらが利用できるプラットフォームである必要があります。
#+end_quote

最近のメモとかは基本的にすべてorg-roamに書き溜めるようにしています、が、リンクをするのがめんどくさいなど、いくつか課題がありますが・・・

** org-roamのjournaling機能
org-roamは、org-modeよろしく非常に多彩な機能が含まれていますが、その中に ~dailies~ という機能があります。

https://www.orgroam.com/manual.html#Daily_002dnotes

org-journalほどは機能があるわけではないけど、必要最低限の機能はあって、かつroamと統合されている・・・というようなのが特徴です。

今の私の設定はこんな感じになってます。

#+begin_src emacs-lisp
  (leaf org-roam
    :after org
    :straight t
    :if (and (file-exists-p my:org-roam-directory))
    :custom
    ((org-roam-db-update-method . 'immediate)
     (org-roam-db-location . my:org-roam-db-location)
     (org-roam-directory . my:org-roam-directory)
     (org-roam-index-file . my:org-roam-index-file)
     ;; dailiesを保存するdirectory
     (org-roam-dailies-directory . my:org-roam-dailies-directory)
     (org-roam-capture-templates . '(("d" "default" plain (function org-roam--capture-get-point)
                                      "%?"
                                      :file-name "%(format-time-string \"%Y-%m-%d--%H-%M-%SZ--${slug}\" (current-time) t)"
                                      :head "#+title: ${title}\n- tags :: "
                                      :unnarrowed t)))
     ;; dailiesのcapture
     (org-roam-dailies-capture-templates . '(("d" "default" entry
                                              #'org-roam--capture-get-point
                                              "* %<%H:%M>\n%?"
                                              :file-name "daily/%<%Y-%m-%d>"
                                              :head "#+title: %<%Y-%m-%d>\n"
                                              :olp ("Journal")))))
    :bind
    ((:org-mode-map
      :package org
      ("C-c r" . org-roam-insert)))
    :hook
    (after-init-hook . org-roam-mode))

#+end_src

この設定だと、captureを起動すると、

#+begin_src org
  ,* 15:01
  <ここにカーソル>
#+end_src

というような表示になります。なので、大体org-journalと同じような使い勝手でサクサク書いていくことができます。

** 書いてみてどうか
基本的にメモというか、もう書捨てであることが確定しているような思考のメモとか、なんとなく見掛けたものの感想とか、そういう脳内のダンプに向いているのかなー、という風に感じますね。

使い方的には、dailiesに書いたものからpermanent noteという形で括りだしていく、という形になるようですが、使い方は人それぞれでもあるので、いくつか使い方を見ていっている感じです。結構permanent noteという形でくくりだしていくのが難しく、これは慣れが必要だなーと思っているところです。

EmacsでRoam Researchを利用してみたいな、という場合には検討してみちゃーどうでしょうか？

* TODO Linuxで音楽を聞く時に使っているもの                       :Linux:雑記:
:PROPERTIES:
:EXPORT_FILE_NAME: audio-player-in-linux
:END:
大分前に購入していたけど、ほとんどやっていなかった[[https://store.steampowered.com/app/1318690/shapezio/?l=japanese][shapez.io]]というゲームを久し振りにやったら、ずっと黙々とやってしまいました。これは時間が溶ける系統や・・・。

さて、今回もライトな話題で、Linuxでの音楽鑑賞をどうやっているか、について書いてみようと思います。

<!--more-->

** GUI or CUI
まず、Linuxでのプレイヤーとしては、CUIベースかGUIベースか、に大別されます。

- CUIベース
  - mplayer
  - [[https://mpv.io/][mpv]]
- GUIベース
  - [[https://www.smplayer.info/ja/info][smplayer]]
  - celluloid
  - [[https://www.videolan.org/vlc/index.ja.html][VLC]]
  - ...など


CUIベースであるmplayer/mpvは、他のplayerのバックエンドとして利用されている(smplayerやcelluloidといったものは、mplayer/mpvのフロントエンドです)ので、実際には本当にインターフェースがCUIなのかGUIベースなのか、という違い程度だと思います。

*** Spotifyとかは？
私は基本的にオールドタイプなので、ストリーミング(有料会員ならオフラインにダウンロードとかできるらしいですが)で聞く、というのは基本的にやってません。購入した楽曲は手元に置いておきたい、という感じですね・・・。

Youtubeとかで見つけても、その後には楽曲をあらためて別サイトで購入したりするのが私にとっては一般的です。

** 楽曲の保存
基本的に全ての楽曲はNASに保存しています。ちなみに使っているNASは二代目で、以下を使っています。

https://www.synology.com/ja-jp/products/DS218

これに、WesternDegitalのNASむけHDDを組み合わせて利用しています。

LinuxとはNFSで接続できるので、まー特に問題ありません。Windowsとの相互運用も問題ないので、普通にWindows機とのファイルのやりとりにも利用しています。

** 何を利用しているのか
私は上記に書いたプレイヤー全部を利用したことがありますが、現状は以下のような形に落ち着いています。

- 音楽をディレクトリごととかで再生する
  - mpv
- 動画や、頻繁にシークする音楽ファイルを再生する
  - celluloid
- プレイリストを見たい
  - celluloid


mpvでもシークはできるんですが、どうしても視覚的に直感的ではないため、シークが頻繁におこなわれるものとしてはcelluloidを利用しています。あと、動画とかを一気に見たりする場合は、プレイリストとして常に表示できるGUIの方が便利です。

#+begin_quote
まぁ、最近は動画についてはストリーミングでしか見ていないので、ほとんどcelluloidは使っていないのですが・・・。
#+end_quote

** なぜCUIを利用するのか
私が思うCUIの楽さ加減としては、

- tmuxとかのターミナルマルチプレクサと併用すれば、裏で流しっ放しにできる
- ディレクトリ内を一括で入れたりするのが簡単
  - ファイル数が多すぎると、コマンドラインの最大長を超える可能性もありますが
- GUIが無いのでとても軽い


という点です。私の環境ではWMとしてswayを利用しているので、GUIを起動するとどうしても邪魔になりやすい、というのがあります。

#+begin_quote
floating windowは、場所をずらしたり調整したり、後邪魔になったときに避けないといけないので、あんまり利用してません。
#+end_quote

** 他の人はどうやってるんだろう
最近はもう基本的にストリーミングサービスを利用している、という方が大半だとは思います。私は今でも専用のメディアプレイヤーにmp3なりを突っ込んで聞いている、という人なので、基本的にはオフラインで聞けることを優先しています。

ストリーミングを利用している人の場合、基本的にはそのサービスのクライアントを利用するんだと思いますが、それって無駄に重いし邪魔じゃない？という思いもあります。
機会があれば聞いてみようかなー、と思います。(私の周辺はみんなオールドタイプなので)

* comment Local Variables                                           :ARCHIVE:
# Local Variables:
# eval: (org-hugo-auto-export-mode)
# End:
