#+STARTUP: content logdone inlneimages

#+HUGO_BASE_DIR: ../../../
#+HUGO_AUTO_SET_LASTMOD: t

* Posts
:PROPERTIES:
:EXPORT_HUGO_SECTION: post/2019/01
:END:

** TODO 格子配列に適したかな入力を模索する                                   :雑記:
:PROPERTIES:
:EXPORT_FILE_NAME: kana_input_for_columner_struggle
:EXPORT_AUTHOR: derui
:END:

以前の記事で、薙刀配列を利用している、と書きましたが、色々思うところがあり、今は別の可能性を探っています。

<!--more-->

現在色々と提案されているカナ入力方式は、TRON配列を除くと、基本的に *一般的なJISキーボードに合わせて設計されています* 。99%の人は、JISキーボードを利用しているであろうから、その課程は至極当然です。

しかし、Ergodoxを始めとする、通称 *格子配列* とJISキーボードでは、押しやすいキーや指の可動範囲がかなり異なります。人差し指が担当する *TYBN* であったり、小指が担当する *PQ* は使い勝手が変わります。また、JISキーボードのようなRow-struggleなキーボードで押しやすいキー連接は、必ずしも格子配列で押しやすいとは限りません。

*** 格子配列の特徴と個人の身体的特徴
格子配列には、次のような特徴があります。（結構個人的な感覚ですが）

- 列をまたいで指を移動するのが厳しい
- 同じ列内での移動はやりやすい


また、これは私の身体的特徴ですが、

- 人差し指と小指がかなり短い
  - 格子配列でT/Yに指を伸ばすのに若干気合が必要なくらい
  - 手ごと移動すれば、指の不可は大分減りますが、今度は腕を持ち上げるという負荷がかかります
- Emacsで小指が結構鍛えられている

という特徴があります。模索している配列では、これらをどう解決していくか？が肝になります。

*** シフトの設計
現在利用しているキーボードであるCrkbdには、そもそも42キーしかなく、親指以外の指に割り当たっているキーは36キーしか存在しません。このうち6キーはCtrlやShiftなので、事実上は30キーが物理的な限界です。

どのみちひらがなだけで50音あるので、必然的に何らかのシフト機構が必要になります。シフト機構にも色々ありますが、大別して次のようなものがあります。

- 前置きシフト
  - JISかな、新JIS、親指シフト、月配列
- 同時シフト
  - 蜂蜜小梅配列、新下駄配列、薙刀配列、飛鳥配列

他にも色々ありますが、要は *シフトに順序性があるかどうか* が大きな違いです。順序性がある場合、ロールオーバーが可能になりますが、ほぼ同時にキーを押下した場合、意図しない入力になる場合があります。
順序性がない場合、ほぼ同時に押下しても問題ありませんが、その代わりに単打時の誤爆が起こりやすくなります。

また、どのキーをシフトとして利用するか？というのも重要です。

- 小指シフト
  - JISかな
- 親指シフト
  - NICOLA、蜂蜜小梅配列、薙刀配列、飛鳥配列
- 人差し指シフト
  - 薙刀配列
- 中指シフト
  - 月配列、新下駄配列


Crkbdに限って言うと、Layer切り替えがかなりの頻度で発生する上、SandS/Enterを親指に割り当てている都合上、これ以上負荷をかけるのはリスクがあります。実際、親指だけ痛くなったことがあるので。そうなると、弱い小指に負荷を与える小指シフトは論外として、人差し指/中指シフトが有力に思えます。
月配列や新下駄配列を利用していても、あまり違和感は無かったので、個人的にも問題はありません。

*** 清濁同置と清濁別置
新下駄配列や飛鳥配列では、清濁別置を選択することで、高効率を実現しています。しかしその分記憶負担が大きく、また運動記憶が確立するまでに時間がかかります。

蜂蜜小梅配列や薙刀配列では、濁音を入力する時に清音＋シフトで入力するようにして、記憶負担を抑えて、連想記憶で思い出せるようにしています。新JISでは後置きで濁点を追加する方式です。

最終的には運動記憶に帰着するため、効率だけで言えば清濁別置の方で効率的なのは明らかです。ただ、滅多に利用しない濁音や半濁音を連想無しで覚えなければならないので、滅多に利用しないかなの入力時にはかなりスピードに影響することが想像できます。

***
* COMMENT Local Variables                                           :ARCHIVE:
# Local Variables:
# org-hugo-auto-export-on-save: t
# End:
