#+startup: content logdone inlneimages

#+hugo_base_dir: ../../../
#+hugo_section: post/2024/01
#+author: derui

* DONE 7sproを組み立てた :雑記:
CLOSED: [2024-01-08 月 15:02]
:PROPERTIES:
:EXPORT_FILE_NAME: build_7spro
:END:
気がつけばあっというまに年が明けまして、そろそろ正月休み気分も投げすてるべきタイミングに来ているような感じです。

ということなので(？)、約2年ちょっと振りにキーボードを組み立てたので、その話を書こうかなと思います。

#+html: <!--more-->

** 今回作ったやつ
まぁタイトルにもありますが、こちらになります。

https://shop.yushakobo.jp/products/7spro

特徴については上記のページにいってもらった方が圧倒的に正しい情報なんですが、さしあたって書くと

- 知ってる人も多いhappyでhackingなキーボードとほぼ同じレイアウト
- 長すぎるスペースをいい感じに分割し、親指で押せるキーを増加
- 表面実装とかソケットとか、めんどくさいところが非常に少ない
  - はんだが必要なのは、pro microとリセットスイッチ、TRRSソケットくらいです
- 無線対応も可能
  - 今回はやりませんでした。理由は後述


設計者は、 https://salicylic-acid3.hatenablog.com/ で活動されているサリチル酸さんです。

** 実際組立難易度はどうだった？
はっきり言えば、以前組み立てたclaw44とは比べ物にならないくらい簡単です。ソケット・ダイオードが全部実装済なので、みんな大好き表面実装との戦いをやる必要がありません。

ただ、今回はなんでか知らないんですがpro microへの書き込みがうまくいかず、

- linuxのqmk
- linuxのremap
- windowsのremap


と試しても、なんでかうまくいかない、というのが一番時間かかりました…。初めてRemapって使ってみましたが、正直native linux持ってるんならdocker使ってやった方が簡単かつ確実な気がしました。

#+begin_quote
これは私がすでにqmk側に大分カスタムを入れているから、という可能性も高いのですが。
#+end_quote

最終的にはttyに書き込めないので、無理矢理chmodしてゴニョる、という力技にて解決してます。これなんとかしないと、単独で書き込みができないからなんとかしたいところです。多分グループかなんかが足りていない？

まぁこれで手間取ったものの、あとはドライバーさえあればどうとでもなる、という感じだったので、良質なキットをお手軽に手に入れたい方はいい感じではないでしょうか。なおロウスタッガードに指が慣れすぎて、Bが滅茶苦茶遠く感じます。いっそパームレストない方がいいんじゃないかとか思ってしまう程度には…。


** キーマップどんなん？
この文章は組み立てたばっかりの7sproで書いているので、まだ指が全然最適化されてないため、まだ暫定ですが、いつもどおり自分のリポジトリに置いてます。

https://github.com/derui/qmk_firmware/blob/master/keyboards/salicylic_acid3/7skb/keymaps/derui/keymap.c

実際触ってみると、親指にある4つのキーの内、 1.5uと2.0uのキーが思ったよりも遠かったです。今迄のclaw44とかと比較すると、大体一番中指側のキーあたりに、大きめのキーがある感じになります。これは触ってみないと中々わかりづらい感じですね。デフォルトのキーマップだと、そこにSPCが置いてあるのですが、ちょっと触ってみた感じでは結構厳しめです。
なので、B/Nの下にある1uのキーに、いつもどおりSandSとSandEnterを導入しています。もうこれが無いと生活できないわ、ってレベルになりつつある…。大きめのキーにはraise/lowerを割り当ててます。今迄40%キーボードを利用していたため、記号の入力がコンビネーション頼りだったため、そこの矯正が結構しんどさがありますね。

後は個人的なカスタマイズで、単独キーでかな/英数を切り替えられるようにしてあります。もっとも、SKKで生活している人(かつ、linuxだとfcitx4 on waylandなので、日本語入力がそもそもEmacs上でしかできないレベル)なので、正直そこまで…っていう感じもありますが。結構親指を曲げないと届かない、というのもあるため、一定layer側に逃がす必要もあるかなぁ、とか現状は考えています。


** この辺がgood/もう一声
基本的には出来自体はとてもよいので、どっちかというと個人的な感想になります。参考にしすぎないように。

*** Good
- 良くも悪くも慣れ親しんだロウスタッガードかつHHKB配列
- 非常に多数のネジで止めるため、剛性がめちゃくちゃ高い
  - そりゃアルミとかの金属と比べたらダメですが、少なくともclaw44よりは剛性が高い印象があります
- スペースバーが長くない
  - 個人的には、日本人にとってあの長いスペースバーには存在価値が無い(暴論)と思っているので、これくらいが丁度いい感じです

*** もう一声
- 親指のキー部分が、もう全部1uでもよかったかもしれない
  - これはErgodox EZ以来、ほぼずっとロウスタッガードかつ親指に最適化されているキーボードを利用している人間の戯言ではある
  - が、Altあたりまでいくと明確に *遠い！* ってなってるので、ここの折り合いをどうつけるか？が、移行に対しての話になりそう
- indicatorのLEDが…大分見えない
  - うっすら見えるんでなんとなくわかるんですが、明るい部屋だともはや「ん？光って…るな」くらいの印象。中々やりづらいとは思うのだけど
   
** 今回のキースイッチ
実は今回、目玉はキーボードではなくキースイッチになります。今迄赤軸とか銀軸とか、原則リニアなものを使ってきましたが、今回高級キースイッチに手を出しました。

https://shop.yushakobo.jp/products/4315?variant=45697298628839

これになります。なんと *1スイッチあたり330円！！！* という破格のお値段です。なおソケットにはめるときにやらかして、さっそく一つオシャカにしました orz。これの特徴は、 *UHMWPE* (ウムピェ？とか読むらしい)という自己潤滑性のある素材100%で作られているというところで、ルブしなくとも非常に滑らかな打鍵感が得られる、としています。
実際これに切り替えてみたところ、今迄のgateronの銀軸とは比較してはならないレベルの滑らかさです。静電容量無接点のキースイッチもRealforce/HHKB Proと触ってきましたし持ってましたが、それと匹敵するかそれ以上かもしれない…という凄さです。

正直そこまで変わるんかいなぁ、と思ってたのですが、これは高い金を出す価値はあると思います。なにより金がかかってる分作りも丁寧で、ガタつきとかもほとんどありません。ただ、おしむらくは若干荷重が重たい、というのが唯一の欠点かな、というところです。アクチュエーションポイント自体はそこまで深くないんですが、結構底打ちしがちな人にとっては、結構重たく感じるかもしれません。これはこれで慣れですが、あえて底打ちしないようにサラサラと打つ感じにすると、不快になるようなノイズもほぼしないです。

ルブしなくてもこれならいける、という人もいるくらいですが、ルブに労力を出すのが嫌だなぁ、とかそういう人はお金で解決できるとは思います。見かけたら触ってみてください

** 久し振りのキーボード刷新
個人で使うキーボードとしては、およそ6年ぶりくらいにロウスタッガードを使っているため、分割しているとはいえ非常に慣れない部分があったりしますが、まぁmacbookのキーボードで打つこともあるので、この文章を打っている内に、思ったよりもすぐ慣れてきました。多分課題はそれじゃなくて、今迄親指で押していたキーをどう負荷を与えすぎない形で逃がすか？というところになっている予感がします。

SandSとSandEは快適すぎて、これなしで打つのはどうしようもないときにしたい、というところなので、lower/raiseといったレイヤーの調整かなぁ、というところですね。なんにせよ、刷新すると気分が変わってくるというのもあります。
新年を迎えて、なんか新しくしたいなぁ、というときには、手元にある道具を変えてみるというのもありなのではないでしょうか。

この文章は7spro + Emacsで書かれました。Escの位置が大分迷子になってます。

* comment Local Variables                                           :ARCHIVE:
# Local Variables:
# eval: (org-hugo-auto-export-mode)
# End:
*
