#+startup: content logdone inlneimages

#+hugo_base_dir: ../../../
#+hugo_auto_set_lastmod: t
#+HUGO_SECTION: post/2020/12
#+AUTHOR: derui

* DONE 引っ越ししたのでPCを新調した話                                  :雑記:
CLOSED: [2020-12-12 土 11:06]
:PROPERTIES:
:EXPORT_FILE_NAME: make_new_pc
:END:
私用でいろいろ忙しかった原因である引っ越しが終わりました。数えたら8年半くらい同じ場所に住んでました。

で、引っ越しを期に自作PCを新調したので、それについて書いてみようと思います。

<!--more-->

** なんで新調したのか？
心機一転、という話もありますが、一番は **使っていたPCがめっちゃでかい** ってことでした。

ちなみに前のPCで使っていたケースはこれです。

Themaltake Urban T81

https://kakaku.com/item/K0000626152/?cid=shop_yahoo_dsa_00010032&yclid=YSS.1000163161.EAIaIQobChMI5MqMh6LH7QIVV3RgCh3HQAkMEAAYAyAAEgLUW_D_BwE

フルタワーケースで、全高が **61cm** あります。このサイズの何が問題というと、実際に問題として感じていたのは以下のような点です。

- 入るPCラックがほとんどない
  - 入手できそうなもので唯一入りそうだったのが[[https://www.amazon.co.jp/PJC-PJC-7201-WD-【上下昇降-51～80cm】サイドデスク・L字デスク・CPUワゴン・パソコンワゴン/dp/B07W7H6LZ4/ref=asc_df_B07W7H6LZ4/?tag=jpgo-22&linkCode=df0&hvadid=342449963937&hvpos=&hvnetw=g&hvrand=6733612781861752480&hvpone=&hvptwo=&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1009303&hvtargid=pla-827085345755&psc=1&tag=&ref=&adgrpid=69189144376&hvpone=&hvptwo=&hvadid=342449963937&hvpos=&hvnetw=g&hvrand=6733612781861752480&hvqmt=&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=1009303&hvtargid=pla-827085345755][これ]]です。これも割とギリギリまで伸ばさないとならなかった・・・。
- 重い
  - スチールラックなので当然ですが、重いです。全部部品が組み込んであると、だいたい20kgくらいになるので、ダンボールに入れるのも一苦労です（でした
- よく考えたらそこまででかくなくていい
  - ディスクの拡張とかそんなにしないし、でかいGPUを積むわけでもないし・・・


また、途中で一回M/Bのメモリ部分が故障してM/BごとCPU/Memory/CPUクーラーを全部新調したことはありますが、都合6年ほどこのケースを使っていたというのもあり、全面新調に至りました。

** とりあえず新しいPCの構成
構成はこんな感じです。大体アッパーミドルくらいかな・・・。

- ケース：Fractal Design Define R6
  - 評判のいい、ミドルタワーケースです
- CPU：Ryzen9 3900XT
- CPUクーラー：Nocture NH-U12A
  - かなり高価なクーラー。しかし、Ryzen9シリーズを空冷で冷やそうとすると、これくらいは欲しかったので
- SSD
  - システム：Crucial M.2 P5(500GB)
  - ストレージ：Crucial MX500 1TB
  - HDDを卒業して、full SSD構成にしました。NVMeも使ってみたかったので。
- Memory：Corsair 16GBx2
- 電源：Corsair RM750
- GPU：Radeon RX 5700XT
- マザーボード：ASRock Steel Legend B550


初めて全面的にAMD構成にしてみました。Ryzenの5xxxシリーズは全滅していたので、潔く3900を使っています。

ちなみにお値段は、しめて21万程度でした。ドスパラでまとめて購入しましたが、BTOでも大体同じくらいの値段になっていたので、まぁ相場通りかな、と。

** 組んだ
大体2時間くらい・・・。毎回組むたび思うのは、システムパネルのケーブルはもうちょっと楽にならんのか・・・。というところですね。

ASUSのM/Bを使ったときにあった、 **Q-Connector** はほんとに楽だったので、これが標準添付されてほしいです。

https://www.pc-master.jp/jisaku/fp-connector.html

ここで紹介されてるみたいなやつです。システムパネルはたいてい最後の方に組み込むことが多いと思うので、割と無理のある姿勢で細かい作業をしないとならないことが・・・。

とりあえずは、ちゃんと動きました。相変わらず最初の起動は緊張しますね。幸い今まで初期不良にはあたったことが無いのですが、ここで動かないときの絶望たるや凄まじいことと思います。

** OSをインストール・・・できない？
さて、このPCにインストールするのは、かれこれ10年くらい使い続けているGentoo Linuxです。ただし、今回はCPUが切り替わるということもあったので、10年ぶりにclean installすることにしました。

いつもの通り、USBにminimal imageを書き込んで起動、さてstage3を持ってくるかー、というタイミングで気づきました。

#+begin_quote
「ネットワーク、つながってない・・・？」
#+end_quote

~ip addr~ をやってみても、確かにloしかデバイスが存在していないです。なん・・だと・・・？と思いながら、おもむろに ~lspci~ を実行してNICを探してみると、こんなやつでした。

#+begin_src shell
  ...
  07:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8125 2.5GbE Controller (rev 05)
  ...
#+end_src

Realtekか・・・。でも今までもRealtekだったしなー、と思いながら、RTL8125というデバイスを検索してみると、なんとこいつのドライバがKernelにmergeされたのは *5.9* のタイミング、とのこと。

どうも相当に新しいNICだったようです。いろんなフォーラムで絶望している人を見かけてます。

翻ってインストールイメージで使われているKernelをバージョンを見てみると、 *5.4.xx* という絶望の表記が見えました・・・。

さて、このデバイスはRealtekからドライバが出ているのですが、この時点ではいろいろ問題があります。

- make/gcc/linux headerがないのでビルドできない
- 仮に外部から持ってきてもstage3とかを持ってこないとbuildできない
- しかしstage3を持ってくるためにはRTL8125のドライバが必要
- buildするためにはstage3が必要・・・


という、堂々巡りになってしまっていました。

** どうしたの？
最終手段として、適当なUSB NICを買ってきてなんとかしました。Gentooでは5.9のkernelとかを普通に入れられるので助かります。

あとは、handbookを参考にインストールするだけです。

- Ryzenだったので、 https://wiki.gentoo.org/wiki/Ryzen これとか
- Radeonだったので、 https://wiki.gentoo.org/wiki/AMDGPU これとか
  - Radeonも、古い世代とNaviとかの新しい世代でGPUの名前が変わっていました


今回はRadeonだったのですが、Firmwareの登録をする必要があり、ここが割とハマりポイントでした。ここで間違うと、起動直後にフリーズするので、きっちり見ましょう。

自分のGPUのmodelが何か？は、lspciの結果に ~Navi 10~ とか書いてあるのでそれを見てもいいし、もしくはWikiに対応表が載ってるので、それを見ても良いかと思います。

** いろいろ変えたのは別の記事で
さて、なんとかインストールできたので、いろいろ環境を整える・・・というところです。

これについては、今回いろいろ変えたので、別の記事で書こうと思います。

今回の教訓としては、新しいNICが入る場合、動作済みのUSB NICとかをお守りに持っておくのを推奨します。特に最近はネットワークにつながっていないとOSのインストールすらできないのがほとんどなので・・・。

* DONE Linux環境をいろいろ変えた話                                     :雑記:
CLOSED: [2020-12-21 月 21:18]
:PROPERTIES:
:EXPORT_FILE_NAME: renewal_desktop_environment
:END:
ふと気づいたら年が終わりそうですね。今年はどこもかしこも大体コロナのせい、という感じになりましたが。

前回PCを新調した話をしましたが、中身も1x年ぶりに新調しました。いろいろ変えたので、その話を書いてみます。

<!--more-->

** どう変えたのか？
前のPCは、最初から数えて10年くらい前に入れたGentooを、自作するたびに移し替えながら使ってきました。しかし、さすがに10年も使っていると、使っていないパッケージとかがうろ覚えになり、いろいろ試行錯誤した設定ファイルが転がっていたり・・・。

NASを導入したので、データ移行自体は難しくなくなったのもありましたが、ちょうどいいタイミングということで、もう一回Gentooを入れてみることにしました。と、いうのが前回の終わりでした。

とはいえ、大きく変わったところは少ないです。dotfilesを使えるようにもしたいし。

** X -> Wayland nativeに
今回のPC構成で最も大きな違いは、NVidiaのビデオカードではない、という点です。Waylandにするにあたって最大の問題となります。

https://wiki.archlinux.jp/index.php/Wayland


安定と信頼のArch Wikiにあるとおり、NVidia以外のドライバは、全て *GBM* というAPIを実装しているのですが、NVidiaだけはこれとは違うAPIを実装しています（そしてGBMを実装する気はサラサラ無いらしい）。Gnome/KDE Plasmaという、Desktop Environmentの二大巨塔はこれを使うような実装もしています。
が、それ以外のコンポジターは、リソースの問題もあり、これを使うことができません。

*NVidia以外の* ということは、AMDのドライバは対応しています。（そしてRyzenの売上で余裕が出たのか、ドライバの出来もかなり良くなってきたというはなしです）

と、いうことで、前々からやってみたかったWayland nativeになってみました。なお、KDE Plasma（Gnomeは個人的に好みじゃない）ではなく、 [[https://github.com/swaywm/sway][sway]]を使っています。理由？i3とほぼ互換だからですよ・・・。

Wayland nativeになってみて、いろいろと良かったところ、悪かったところがありますので、いろいろと書いていこうと思います。


*** Pros: 120fpsとかが普通に使える
Xは、その設計された歴史的経緯のようなものがあって、60hzより高いFrame rateを利用できません。また、今はなきXineramaとかを使っても、完全なデュアルディスプレイは不可能でした（全体として大きな一枚のディスプレイとしてしか扱えないらしい）。

Waylandは、そういう事情も含めて設計されたプロトコルなので、完全な複数ディスプレイ環境や、120hzなどの高いframe rateを利用できます。実際、現在120hzで設定していますが、全く問題なく表示できてます。

*** Pros: 動画などもド安定する
Xのときは、動画を再生したりすると、X server自体がかなりのCPUを食ってしまい、60fpsとかをちゃんと出すのが難しかったです。しかし、Waylandは最初からGPUを使い倒すことを念頭に置いているので、描画周りは圧倒的になめらかです。

Youtubeの詳細などを見ていても、drop frameがほとんど発生しなくなりました。

*** Pros: フォントがきれい
UI上のフォントも、基本的にすべてきれいなアンチエイリアスがかかっています。個人的にはmacOSより見やすいかなと。

*** Cons: 日本語入力が使えない
いいことばかりではなく、Xと比較して新しいので、いろいろ問題があります。日本人で一番問題なのは、Wayland nativeなアプリケーションに対して日本語入力する方法がない、という点です。

これは、WaylandのprotocolにあるIMの実装がいろいろバラバラ・・・という話があるようです。一例だと、swayではversion 2を実装しているが、ibusではversion 1を実装している・・・といった具合です。（fcitx5ではversion 3を実装？しているらしいです）

例外としては、XwaylandというWayland上でXアプリケーションを動作させるためのレイヤーをかました場合です。この場合、アプリケーションとしてはX serverで動いているのと同じなので、fcitx/ibusといったような、XでのIMを使えます。なので、

1. Emacsなど非Wayland nativeなアプリケーションで日本語入力
2. コピる
3. Wayland nativeなアプリケーションに貼り付ける


・・・という、なんだかなぁ、という状況になります。この点は、CJKなユーザーがWaylandを使う上での障壁になっていると思います。

*** Cons: System trayがうまく使えない
swayにはsystemtrayが実装されていますが、いろいろ制約が強いです。

- Dropboxとかは表示できない
- fcitxは表示できるが、操作ができない


** いろいろあるけど、Waylandはだいぶ使えます
日本語入力をするアプリケーションをWaylandで使うのは無理ですが、そういうのはXのアプリケーションとして使えば大体なんとかなる、というところまで来ていると思います。

Chromium/FirefoxなどもWayland nativeで動作するようになっており、かなりスムースな動作をしますし、swayは非常に良くできていて、i3から移行しても特に問題ありません。

いきなり自分のデスクトップで試すのは怖い・・・という場合は、sddmとかlightdmとかを入れていれば切り替えられるので、NVidia以外のGPUを使っている方は、年末年始に籠もっている間に試してみちゃーいかがでしょうか。

* comment Local Variables                                           :ARCHIVE:
# Local Variables:
# eval: (org-hugo-auto-export-mode)
# End:
