#+startup: content logdone inlneimages

#+hugo_base_dir: ../../../
#+hugo_auto_set_lastmod: t
#+HUGO_SECTION: post/2021/05
#+AUTHOR: derui

* DONE Subnauticaをやっている話                                        :Game:
CLOSED: [2022-04-03 日 13:57]
:PROPERTIES:
:EXPORT_FILE_NAME: subnautica
:END:
気付いたら五月の半ばが過ぎてました。最初の一週間はGWだったんで、そこまで過ぎている感じはありませんでしたが。

さて、最近仕事で手を動かしていると、趣味で手を動かすのが億劫になってしまっていてネタが無いので、久し振りにゲームの話をちょこっと書いてみます。

#+html: <!--more-->

** どんなゲームか？
https://store-jp.nintendo.com/list/software/70010000030088.html

↑はSwitch版ですが、元々は2018年にPC版がリリースされています。コンシューマはその後ですね。PC版は、その後2021年の末までアップデートが継続して行われており、ワイドディスプレイなどにも対応していたりします。
なんだかんだ、記事を書いている時点からすると四年くらい前のゲームですね。

#+begin_quote
実は大分前から買ってあったんですが、普通に積んでました
#+end_quote

非常に評価は高く、Steamでは一貫して *圧倒的に好評* を保ちつづけていることからも、その完成度は鉄板となってます。

さてどんなゲームなのか？ですが、 *海ばっかある惑星に不時着したので頑張って帰ろう* というFPS×サバイバルクラフトになってます。サバイバルなので、飢えや渇きといった概念もあるため、放置しているとさっくりと死んじゃいます。

選択できるモードとしては、

- イージー
  - サバイバルよりは優しい
- サバイバル
  - 一般的なモード
- パーマデス
  - 一回死んだら終わりです
- クラフト
  - 制限無しで基地の構築ができます


が選択できます。私は基本的にビビリなので、一撃オワタ式(古い)は強制されない限りは選択しないので、サバイバルでプレイしてます。

#+begin_example
ただし、FPSであること + 水中なので上下の概念なくグルグルしたりするため、酔いやすい人は速効で酔うかもしれません
#+end_example

** 何が楽しいのか
ある種のメトロイドヴァニラっぽく、以下のようなサイクルで探索を進めていきます。

- 周辺を調べる
- 怪しいところを調べて設計図を探す
- 設計図からなんか作ってみる
- 通信から他のところに行って設計図を探す
  - 他にも不時着した人がいるので、たまに通信が来たりします
- 設計図からなんか作ってみる
- ・・・


という感じです。 *設計図を手に入れることで探索範囲を広げるものが手に入る* ので、 *材料を集めて作ってまた探索する* というのを繰り返します。個人的にはこのサイクルがメトロイドっぽいなーと思いました。

さて、それだけだと楽しいのかわかんないですけども、個人的には楽しいと感じたのは以下のような点でした。

*** 地図が無いのでガチ探索
こういうのには珍しく？システムに地図という概念がありません。あるのは方角だけ(それも進めないと無いので、最初はまさに手探りです)です。もし地図が欲しかったら、文字通り自分で書く必要があります。実際に三角測量の原理で地図を書いている人とかもいました。

ビーコンなどのシステムはありますが、それらも結局自分で置かないといけないので、それを置くような場所までは、一度自分でいきつく必要があります。これをめんどくさいと捉えるかどうかですが、私は意外と楽しんでやれてます。
元々風景を記憶するのは苦手ではないから、というのもあるかもしれません。

*** 捕食者の恐怖
海ばっかなので、当然ながら捕食者もいます。このゲーム、 *基本的に捕食者には無力です* 。一応対抗することもできますが、素材がもったいないです。特にリヴァイアサン級と呼ばれる、名前的にヤバい奴等については、 *逃げの一択* です。

とはいえ、システム的には縄張りがあるため、グルっと大回りすると回避できたりします。大自然の脅威には人間は無力だ・・・というのが実感できます。無茶する意味が無いので、経路を考える楽しさがあります。

*** 設計図を見つけたときの高揚感
こういうクラフトだとあるあるだと思いますが、作れるものが増えたり、より広い範囲を探索できるものが手に入ると、それだけで気分がアガってきます。

ある程度進むと、大体解放しつくすので、探索オンリーになるのですが、まぁそれはしょうがないかなという。

** システムに対する不満点
実際、サバイバルクラフトとしては必要十分なシステムが揃っているのですが、個人的にはもうちょっとだけなんとかならんかなーと思ったのは以下の点でした。

- 自動航行というか自動前進が欲しい
  - 途中で乗りものに乗れるのですが、結構長い間前進していると、ずっと ~W~ を押していないといけないです。なかなかに指が辛い。
- インベントリが絶妙に少ない
  - これもまた絶妙ではあるのですが、帯に短し襷に長しを地で行くような容量になってます。ま、乗り物を使っていればいいんですが
- HUDの切り替えができるようにしてほしかった
  - 一部のHUDは、切り替えする場合は毎回装備を外したりする必要があります。切り替えられたら最高でした


とはいえ、やはりプレイにおける応答性などは問題なく、そこまでストレス無くプレイできます。

** 興味があればどうぞ
書きませんでしたが、探索においては惑星自体の謎を解いていく、というのが実際のメインであり、そこもまた結構興味深いものとなっています。

FPSなので人を選ぶかもしれませんが、色々わかってきて進められるようになってくると、結構夢中でプレイしてしまいます。セールなどもやっているので、興味とタイミングがあればどうぞ。

*リーパーは怖いぞ*

* comment Local Variables                                           :ARCHIVE:
# Local Variables:
# eval: (org-hugo-auto-export-mode)
# End:
